### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'clip'

### ISSUE THREAD

**Issue by mingyanglei** [sniklaus/pytorch-hed#14]
Hi there, it seemed that your latest commit(https://github.com/sniklaus/pytorch-hed/commit/5ef88c378053e0c865f4a60eb69db4c7f2714e8e) didn't work well with PyTorch 1.6? After `python run.py`, I got the following error,

Traceback (most recent call last):
  File "run.py", line 154, in <module>
    PIL.Image.fromarray((tenOutput.clip(0.0, 1.0).numpy().transpose(1, 2, 0)[:, :, 0] * 255.0).astype(numpy.uint8)).save(arguments_strOut)
AttributeError: 'Tensor' object has no attribute 'clip'

When I changed the `clip` back to `clamp`, it worked. Could you be so kind to provide me with any clues on this? Thanks.

**Comment by sniklaus** [comment]
The two are doing the same thing, `clip` is an alias for `clamp`: https://pytorch.org/docs/stable/generated/torch.clip.html

I switched it to `clip`, which got added to PyTorch in version `1.7.0`, since that is what NumPy is using too.
